<?php
/**
 * @file
 * A description of what your module does.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function dorpa_interface_theme($existing, $type, $theme, $path): array
{
  return [
    'dorpa_jumbo' => [
      'variables' => [
        'article' => []
      ]
    ],
    'social_buttons' => [
      'variables' => []
    ],
    'homepage' => [
      'variables' => [
        'opponent' => [],
        'human_rights' => [],
      ]
    ]
  ];
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function dorpa_interface_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode)
{
  if ($entity instanceof NodeInterface and $entity->bundle() == 'victime') {
    $build['#attached']['drupalSettings']['victims'][$entity->id()] = [$view_mode, $entity->get('field_victim_since')->date->format('Y/m/d')];
  }
}
